<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Beyond Unit Tests End-to-End Web UITesting</name>
   <tag></tag>
   <elementGuidId>5bcfda44-0db4-4f5d-820c-45a7ac194e5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-11369']/a/header/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.entry-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ac3e6c0a-7bc7-4f4e-95d3-ff2f532c2dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entry-title</value>
      <webElementGuid>5adba18c-bb41-48d0-a6cb-4ff025ccaa95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beyond Unit Tests: End-to-End Web UI Testing</value>
      <webElementGuid>f7d1596c-4172-4f69-b8b1-6226b80de500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-11369&quot;)/a[1]/header[@class=&quot;entry-header&quot;]/h1[@class=&quot;entry-title&quot;]</value>
      <webElementGuid>b7bd5915-b296-49db-838f-5911c3a0008b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-11369']/a/header/h1</value>
      <webElementGuid>b388ec5b-cf91-4335-b589-1f694a3ecc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results for: web ui'])[1]/following::h1[1]</value>
      <webElementGuid>1c75aeda-3cfb-42d2-a522-fca411b825e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for:'])[1]/following::h1[2]</value>
      <webElementGuid>fe3f73be-30e3-4db2-bccb-50a3d3433df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='automation'])[1]/preceding::h1[1]</value>
      <webElementGuid>fee40353-2062-47da-b413-dc84dc1a7459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BDD'])[2]/preceding::h1[1]</value>
      <webElementGuid>4de1ad2a-130d-469c-a9ca-d7054b3efaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beyond Unit Tests: End-to-End Web UI Testing']/parent::*</value>
      <webElementGuid>c905082b-fa95-4459-8760-4b175423cdcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/header/h1</value>
      <webElementGuid>ce2d7fbf-0809-4217-a67d-85015d6826b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Beyond Unit Tests: End-to-End Web UI Testing' or . = 'Beyond Unit Tests: End-to-End Web UI Testing')]</value>
      <webElementGuid>6f76787b-9784-4638-9db8-ad958a001650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
