<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hey You were already subscribed</name>
   <tag></tag>
   <elementGuidId>fd73d334-f0d9-452b-8ad3-56b57a3fef70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subscribe-blog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subscribe-blog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de65098b-3358-4afa-b131-a2a62c8fd794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subscribe-blog</value>
      <webElementGuid>13912f92-e683-4d85-abcf-d57e4b76eafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jetpack-sub-notification</value>
      <webElementGuid>9e0e4cd3-a388-4c81-9b23-6ba36442fb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hey! You were already subscribed.</value>
      <webElementGuid>e6ee23ff-f711-47cd-993a-1e65a1f1b20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscribe-blog&quot;)</value>
      <webElementGuid>15a2b5ef-2552-4e22-9b08-59855a25a8c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='subscribe-blog']</value>
      <webElementGuid>0cbff347-41a2-4aad-854a-702cfd41ef3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='blog_subscription-12']/div</value>
      <webElementGuid>7b1b6fa0-6e65-495f-b370-657f02189afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Blog via Email'])[1]/following::div[1]</value>
      <webElementGuid>c8e939de-a1d2-40bb-ba0f-77aaa7c08a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Δ'])[1]/following::div[3]</value>
      <webElementGuid>0c272b89-6d22-42a5-9f80-1b1a9146189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::div[1]</value>
      <webElementGuid>dbba863a-f897-4701-8e4d-349fe6e603b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agile'])[1]/preceding::div[1]</value>
      <webElementGuid>ce25e713-db88-42c2-a676-f930d549d4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hey! You were already subscribed.']/parent::*</value>
      <webElementGuid>8d4a854c-e5bc-4ef4-a695-a1fc9f788d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div</value>
      <webElementGuid>8e171e5a-df83-4baf-bc44-ee0cfe640d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'subscribe-blog' and (text() = 'Hey! You were already subscribed.' or . = 'Hey! You were already subscribed.')]</value>
      <webElementGuid>34361f7b-4563-45e5-8046-5ad2b6b016ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
