<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you You can now check your email _c277fd</name>
   <tag></tag>
   <elementGuidId>3dd41f05-f239-43b9-b935-0a9b39f6b8bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subscribe-blog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subscribe-blog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e8a7455-21c1-4493-9197-885c1e4333da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subscribe-blog</value>
      <webElementGuid>0da0fef8-235b-4f6a-8c77-3aec19e74399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jetpack-sub-notification</value>
      <webElementGuid>838fb8b3-c467-4810-a279-90e9dcd575eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you! You can now check your email to confirm your subscription.</value>
      <webElementGuid>5e953cf3-afb6-4212-a62e-3e34342791d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscribe-blog&quot;)</value>
      <webElementGuid>6aa0372c-09d8-491c-9230-0618b5f24a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='subscribe-blog']</value>
      <webElementGuid>d6973da2-1152-4f5b-81dc-12db11d1d787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='blog_subscription-12']/div</value>
      <webElementGuid>c911b197-e800-4a5c-9e89-1298de3fff7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Blog via Email'])[1]/following::div[1]</value>
      <webElementGuid>35e5f635-1561-434c-819f-f21c12bfea35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Δ'])[1]/following::div[3]</value>
      <webElementGuid>5a96df8e-1c44-4e6d-8007-5d12262e934d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::div[1]</value>
      <webElementGuid>bd0b8b70-5c9a-431a-9c59-31616cd72d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agile'])[1]/preceding::div[1]</value>
      <webElementGuid>64f2255b-2f89-46f7-91de-eec691b4d8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you! You can now check your email to confirm your subscription.']/parent::*</value>
      <webElementGuid>323318ac-b5b1-4b69-b746-89c9341924d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div</value>
      <webElementGuid>6a1af2ba-6b69-4986-85c4-a04c16e0eb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'subscribe-blog' and (text() = 'Thank you! You can now check your email to confirm your subscription.' or . = 'Thank you! You can now check your email to confirm your subscription.')]</value>
      <webElementGuid>2708be63-805c-4170-828f-1c0970a6767b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
