<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_It seems you already tried to subscribe_7e49bc</name>
   <tag></tag>
   <elementGuidId>ba2f1a06-429e-41f5-994b-3fe1cb448959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subscribe-blog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subscribe-blog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0b89847-630a-4359-8a42-184bce8b9e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subscribe-blog</value>
      <webElementGuid>e91accac-37cc-4e97-b471-027641d1026d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jetpack-sub-notification</value>
      <webElementGuid>5587cfb2-aa81-4e5a-88be-bf18d761fae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>It seems you already tried to subscribe. We just sent you another email so you can confirm the subscription.</value>
      <webElementGuid>c9f27fd8-1a88-4d54-8113-582234f5df32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscribe-blog&quot;)</value>
      <webElementGuid>c2327678-20a5-4e52-af90-e458d0a826f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='subscribe-blog']</value>
      <webElementGuid>4b613272-eb46-4d12-944d-878512df4718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='blog_subscription-12']/div</value>
      <webElementGuid>8741930a-6bbf-43af-8079-1db6eb940296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Blog via Email'])[1]/following::div[1]</value>
      <webElementGuid>607d45cc-6e46-47ca-aad2-7a0d65afeafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Δ'])[1]/following::div[3]</value>
      <webElementGuid>6ed723dd-511e-4e40-af88-41ad54fac063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::div[1]</value>
      <webElementGuid>bcf051df-fa04-4e69-a513-f8a602f82821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agile'])[1]/preceding::div[1]</value>
      <webElementGuid>a9d68902-c5bf-44a1-a372-5dbc7f9e34da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='It seems you already tried to subscribe. We just sent you another email so you can confirm the subscription.']/parent::*</value>
      <webElementGuid>546572db-ce5b-4c91-b6b5-2c5833162b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div</value>
      <webElementGuid>b3bad036-fd94-41d5-adaa-61e24b15de92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'subscribe-blog' and (text() = 'It seems you already tried to subscribe. We just sent you another email so you can confirm the subscription.' or . = 'It seems you already tried to subscribe. We just sent you another email so you can confirm the subscription.')]</value>
      <webElementGuid>e4fc0454-abba-4945-8637-3c762f111f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
