<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you You can now check your email _c277fd (2)</name>
   <tag></tag>
   <elementGuidId>5e181aee-c455-4dff-af49-84cd814001f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subscribe-blog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subscribe-blog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9fdee389-65f2-43f8-be02-738d366a192c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subscribe-blog</value>
      <webElementGuid>6513fced-93c6-4207-aa70-fdf03118719f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jetpack-sub-notification</value>
      <webElementGuid>e4d17f99-2960-47a9-a927-51bc435bc33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you! You can now check your email to confirm your subscription.</value>
      <webElementGuid>bc9c472b-605f-46f8-b458-03798bf99e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscribe-blog&quot;)</value>
      <webElementGuid>dbc5d9c9-e4ec-4253-934b-0468d32d3822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='subscribe-blog']</value>
      <webElementGuid>ed0f60a6-4858-4ca4-b5ac-d044c9f4b491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='blog_subscription-12']/div</value>
      <webElementGuid>32de982a-d9e2-43ab-9ece-664bbfd1cad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Blog via Email'])[1]/following::div[1]</value>
      <webElementGuid>27f5eb28-03e9-4d33-991e-0416b7799aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Δ'])[1]/following::div[3]</value>
      <webElementGuid>b177a539-5c64-4c8a-9b62-46edfaa435ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::div[1]</value>
      <webElementGuid>d864df39-d746-4cde-aded-46f0a9375e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agile'])[1]/preceding::div[1]</value>
      <webElementGuid>9966b190-bb58-49c7-97e1-fe38e3c3450c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you! You can now check your email to confirm your subscription.']/parent::*</value>
      <webElementGuid>dcb0cc1e-fa33-4668-8ef0-f6d0297857ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div</value>
      <webElementGuid>a1f3f918-07f9-46e2-81e3-3af7864d3853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'subscribe-blog' and (text() = 'Thank you! You can now check your email to confirm your subscription.' or . = 'Thank you! You can now check your email to confirm your subscription.')]</value>
      <webElementGuid>e152fc53-3e2d-45d3-a745-387d695cc16a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
