<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you You can now check your email _c277fd (1)</name>
   <tag></tag>
   <elementGuidId>353858c4-e8f3-48b6-9ccc-daab901caef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subscribe-blog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subscribe-blog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c40b969-e8d1-46cf-84d7-5a3fba44bc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subscribe-blog</value>
      <webElementGuid>366e183a-68e8-4bc6-8d2b-e63ef142a951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jetpack-sub-notification</value>
      <webElementGuid>d7d0e2ec-f1ab-4a6c-aa5d-fa10f39c96b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you! You can now check your email to confirm your subscription.</value>
      <webElementGuid>8c8d6c90-1634-4016-b826-774dfacea769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscribe-blog&quot;)</value>
      <webElementGuid>9f463c95-a35f-4507-8c85-992b399caeba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='subscribe-blog']</value>
      <webElementGuid>45617b80-30fe-4e22-995d-4637b8285d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='blog_subscription-12']/div</value>
      <webElementGuid>d60400e8-48cf-49da-9d51-784b891ce22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Blog via Email'])[1]/following::div[1]</value>
      <webElementGuid>54a64559-4e1f-4365-b547-95fd561e5a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Δ'])[1]/following::div[3]</value>
      <webElementGuid>c35845ea-9167-45d6-994c-c13aa676d89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::div[1]</value>
      <webElementGuid>8932d457-a38a-413d-9955-3b8102f6bcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agile'])[1]/preceding::div[1]</value>
      <webElementGuid>b0fa431f-b6dc-45ab-8a5f-012c9e6e7a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you! You can now check your email to confirm your subscription.']/parent::*</value>
      <webElementGuid>0081045b-58fd-491a-902f-45f88f56a1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div</value>
      <webElementGuid>c6987401-33ff-4ce8-9d0f-4ab1beda8b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'subscribe-blog' and (text() = 'Thank you! You can now check your email to confirm your subscription.' or . = 'Thank you! You can now check your email to confirm your subscription.')]</value>
      <webElementGuid>bc305cfb-142e-4c94-ba08-3a655b63504d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
