<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search for_s</name>
   <tag></tag>
   <elementGuidId>81241ba8-2854-4a30-8e19-19a3ba14e518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='s']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;s&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b51e283-2e12-4915-9905-ff0abdc4bbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>24ca5658-805d-48ad-ab36-489b5abc9bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-field</value>
      <webElementGuid>77a1ccb3-5d43-4806-a6dd-907d3876b31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search …</value>
      <webElementGuid>1f119ad7-450f-47d6-b14d-54dc0e1828bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>49e017c9-8eb6-485e-8b4b-45bdbf8a1fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-navigation&quot;)/form[@class=&quot;search-form&quot;]/label[1]/input[@class=&quot;search-field&quot;]</value>
      <webElementGuid>92ce508c-2512-4417-a2bb-871ea310ee37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='s']</value>
      <webElementGuid>1b085af4-2be7-4de6-837d-ccdb4e5fa00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='site-navigation']/form/label/input</value>
      <webElementGuid>f6e02c00-1e3d-4634-a625-2fdf969138c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1da349ad-8e98-410f-b148-f937e16df4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search …' and @name = 's']</value>
      <webElementGuid>b213de46-35fc-4b54-bcf1-104be386ebeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
