<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search for_s (1)</name>
   <tag></tag>
   <elementGuidId>15f59d94-04a1-4346-b617-89274aefd9fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='s']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;s&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b577cf0c-da14-4824-9f6a-27bf29336207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>8e417d08-f8b2-40a8-bf8f-adc6c5caed66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-field</value>
      <webElementGuid>937a2e5a-47ea-4eda-9221-3ccab3a621e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search …</value>
      <webElementGuid>0af4c14b-8483-4ff2-b96a-cad304223143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>60710b01-2d32-4210-8d3f-be1c95ec9013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-navigation&quot;)/form[@class=&quot;search-form&quot;]/label[1]/input[@class=&quot;search-field&quot;]</value>
      <webElementGuid>fc54ee48-0e84-486d-b118-34b89355deb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='s']</value>
      <webElementGuid>7ca59b3d-f74c-4291-b4e4-0b36f2e2e966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='site-navigation']/form/label/input</value>
      <webElementGuid>aed34006-0fb9-4adb-aad2-9ba24f512a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fba7d8c2-d985-4825-bef5-5fda357063d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search …' and @name = 's']</value>
      <webElementGuid>5b943f2a-9c5c-46a2-99e3-2c6916baefc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
